# start mongo with "brew services start mongodb"

#spring:
#  profiles:
#    active: dev
#---
spring:
  r2dbc:
    url: r2dbc:h2:mem://testdb
  config:
    activate:
      on-profile: sql
  data:
    r2dbc:
      repositories:
        enabled: true

---
spring:
  data.mongodb:
    host: localhost
    port: 27017
    database: reactive-test
  config:
    activate:
      on-profile: dev
---
spring:
  data.mongodb:
    host: localhost
    port: 27017
    database: local
  config:
    activate:
      on-profile: nonprod
---
spring:
  data.mongodb:
    host: localhost
    port: 27017
    database: local
  config:
    activate:
      on-profile: prod
---
spring:
  config:
    activate:
      on-profile: test