# start mongo with "brew services start mongodb"

#spring:
#  profiles:
#    active: dev
#---
spring:
  r2dbc:
    url: r2dbc:mysql://localhost/reactive_items_db
    username: devuser
    password: devuser
  config:
        activate:
          on-profile: sql
  datasource:
    data: data.sql
    schema: schema.sql
mydb:
  name: reactive_items_db
---
spring:
  data.mongodb:
    host: localhost
    port: 27017
    database: reactive-test
  config:
    activate:
      on-profile: dev
---
spring:
  data.mongodb:
    host: localhost
    port: 27017
    database: local
  config:
    activate:
      on-profile: nonprod
---
spring:
  data.mongodb:
    host: localhost
    port: 27017
    database: local
  config:
    activate:
      on-profile: prod
---
spring:
  r2dbc:
    url: r2dbc:mysql://localhost/testdb
    username: devuser
    password: devuser
  config:
        activate:
          on-profile: test
  datasource:
    data: test-data.sql
    schema: test-schema.sql
mydb:
  name: testdb